import React from "react"
import { Text } from "./Text"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Text,
  "https://www.figma.com/design/fWOC4cgldpU7HJEiR2kTIO?node-id=2087%3A8487",
  {
    props: {
      text: figma.string("Text"),
    },
    example: (props) => <Text />,
  },
)
